version: "3.9"
services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_DB: modern_dentistry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "012345"
    ports:
      - "5432:5432"
    networks:
      - modern-net

  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    networks:
      - modern-net

  modern-dentistry:
    image: rustemh/modern-dentistry:latest
    container_name: modern-dentistry
    depends_on:
      - postgres-db
      - redis-server
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "5555:5555"
    networks:
      - modern-net

networks:
  modern-net:
    driver: bridge
